### PR TITLE
Create pt.md

### PR DESCRIPTION
**Pull request by maique**
Portuguese translation

### CODE REVIEW

**Review by newbold — APPROVED** [review]

**Comment by newbold** [comment]
Epic, thank you!

**Comment by maique** [comment]
You're very welcome. I wasn't even aware of this one, and it's such a small file, I had to do it.

**Comment by newbold** [comment]
@maique, if you’d like to be credited for the translation, just say the word! I need to add that to some kind of standard template or something so folks know that they can get a credit and link for translations (if desired).

**Comment by maique** [comment]
No need, thanks for asking. It was really no work.

**Pull request merged**
